spring.application.name=currency-converter

spring.datasource.url=jdbc:postgresql://localhost:1023/converter_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=db/changelog/db.changelog-master.xml